# Generated by Django 4.2.7 on 2023-11-15 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0002_todomodel_user_alter_todomodel_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todomodel",
            name="time",
            field=models.DateField(blank=True, null=True),
        ),
    ]
